# fix z
CUDA_VISIBLE_DEVICES=2 python test_universal.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --heavy_obstacle --random_gripper --num_timesteps 1e7 --log_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/her_sac
CUDA_VISIBLE_DEVICES=2 python test_universal.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --heavy_obstacle --random_gripper --num_timesteps 1e7 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac
# fix z, augment
CUDA_VISIBLE_DEVICES=0 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --n_subgoal 4 --log_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/her_sac_augment/0
# CUDA_VISIBLE_DEVICES=0 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --n_subgoal 10 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment
# Tweaked hard case config
CUDA_VISIBLE_DEVICES=0 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --n_subgoal 4 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_1
CUDA_VISIBLE_DEVICES=2 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --hack_augment_time --n_subgoal 4 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_hack/0
# CUDA_VISIBLE_DEVICES=1 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/her_sac/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --n_subgoal 20 --random_ratio 0.0 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.0_fixz/her_sac_augment_hack/0
# CUDA_VISIBLE_DEVICES=1 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/her_sac/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --hack_augment_policy --n_subgoal 5 --random_ratio 0.0 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.0_fixz/her_sac_augment_hack/1
CUDA_VISIBLE_DEVICES=1 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --hack_augment_policy --n_subgoal 1 --random_ratio 0.0 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.0_fixz/her_sac_augment_hack/3
CUDA_VISIBLE_DEVICES=1 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 2e6  --hack_augment_policy --n_subgoal 1 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_hack/1
CUDA_VISIBLE_DEVICES=2 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e6 --augment_when_success --hack_augment_policy --n_subgoal 4 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_hack/2
CUDA_VISIBLE_DEVICES=1 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success  --n_subgoal 1 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_hack/3
CUDA_VISIBLE_DEVICES=2 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e6 --augment_when_success  --n_subgoal 4 --random_ratio 0.7 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.7_fixz/her_sac_augment_hack/4
CUDA_VISIBLE_DEVICES=3 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success --hack_augment_policy --n_subgoal 1 --random_ratio 0.3 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.3_fixz/her_sac_augment_hack/0
CUDA_VISIBLE_DEVICES=3 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --augment_when_success  --n_subgoal 1 --random_ratio 0.3 --log_path logs/FetchPushWallObstacle-v4_heavy_random0.3_fixz/her_sac_augment_hack/1

# fix z, augment no filter
CUDA_VISIBLE_DEVICES=0 python test_universal_augment.py --env FetchPushWallObstacle-v4 --policy CustomSACPolicy --trained_model logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/final.zip --heavy_obstacle --random_gripper --num_timesteps 1e7 --buffer_size 2e6 --n_subgoal 1 --log_path logs/FetchPushWallObstacle-v4_heavy_purerandom_fixz/her_sac_augment_nofilter/0
# ensemble
CUDA_VISIBLE_DEVICES=2 python test_ensemble.py --env FetchPushWallObstacle-v4 --policy EnsembleCustomSACPolicy --batch_size 128 --buffer_size 2e6 --heavy_obstacle --random_gripper --num_timesteps 1e7 --log_path logs/FetchPushWallObstacle-v4_heavy_purerandom/her_sac_ensemble

# ensemble
CUDA_VISIBLE_DEVICES=1 python test_ensemble.py --env FetchPushWallObstacle-v4 --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom/her_sac_ensemble/model_0.zip --play --heavy_obstacle --random_gripper
# Visualization.
# CUDA_VISIBLE_DEVICES=2 python test_universal.py --env FetchPushWallObstacle-v4 --heavy_obstacle --random_gripper --load_path logs/FetchPushWallObstacle-v4_heavy_purerandom/her_sac/custom/final.zip --play
